name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: |
          corepack enable
          corepack use yarn@4.3.0
          yarn install
      - run: yarn run build:demo
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
