name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          corepack enable
          corepack use yarn@4.3.0
          yarn install

      - name: Build
        run: yarn build

      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
